fix(cd) disable uv cache
prior run error'd with:
```
No cache found at: /home/runner/work/_temp/setup-uv-cache
Error: Cache path /home/runner/work/_temp/setup-uv-cache does not exist
on disk. This likely indicates that there are no dependencies to cache.
Consider disabling the cache input if it is not needed.
```
so we are disabling the cache